# Assignment 5 — Option B: Job Fit Analyzer
## BSAN 6200: Text Mining & Social Media Analytics — Spring 2026

**Student Name:** Brandon Acosta

**Date:** May 12, 2026

**Option:** B — Job Fit Analyzer  

**API Path:** Paid

---

### Table of Contents
1. [Setup and Imports](#1-setup)
2. [Load Job Descriptions and Resume](#2-loading)
3. [Text Chunking](#3-chunking)
4. [Embedding and Vector Store](#4-embedding)
5. [Analysis Prompts and Chain](#5-analysis)
6. [Zero-shot vs. Few-shot Comparison](#6-comparison)
7. [Evaluation](#7-evaluation)

> **Reminder:** The Streamlit app is a separate file (`streamlit_app.py`). This notebook builds and tests the analysis pipeline.  
> See the Option B Implementation Guide for detailed step requirements.

---
<a id="1-setup"></a>
## 1. Setup and Imports

Install required packages and load your API key from a `.env` file.  
**Do NOT hardcode API keys in this notebook.**

Suggested packages: `langchain`, `langchain-openai` or `langchain-community`, `chromadb` or `faiss-cpu`, `pypdf`, `python-dotenv`, `pandas`, `sentence-transformers` (free path)

In [6]:
import os
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

openai_api_key = os.getenv("OPENAI_API_KEY")

if openai_api_key:
    print("OpenAI API key loaded successfully.")
else:
    print("OpenAI API key not found. Check your .env file.")

OpenAI API key loaded successfully.

In [23]:
# ── Install packages (uncomment as needed) ──
#!pip install langchain-core
#!pip install langchain_openai
#!pip install langchain-text-splitters
#!pip install langchain-chroma
#!pip install langchain_community

# ── Load API keys from .env ──
import os
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

# ── Your imports below ──
from pathlib import Path
from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings, ChatOpenAI

try: 
    from langchain_chroma import Chroma 
except ImportError: 
    from langchain_community.vectorstores import Chroma

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

In [27]:
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small",
    api_key=openai_api_key
)

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
    api_key=openai_api_key
)

test_vector = embeddings.embed_query("Testing the embedding model for the Job Fit Analyzer.")

print("Embedding model loaded successfully.")
print("Vector length:", len(test_vector))

test_response = llm.invoke("Reply with exactly: model connection successful")

print(test_response.content)

Embedding model loaded successfully.
Vector length: 1536
model connection successful

---
<a id="2-loading"></a>
## 2. Load Job Descriptions and Resume

**Required:**
- 10+ JD files in `data/job_descriptions/` (each as a separate .txt or .pdf)
- Your resume in `data/resume/`
- A metadata file `data/jd_metadata.csv` with columns: filename, company, title, source_url, date_collected

Print: number of JDs loaded, number of resume docs, and preview content from each.

In [31]:
# ── Load JD metadata ──

from pathlib import Path
import pandas as pd

# Define project paths
DATA_DIR = Path("../data")
JD_DIR = DATA_DIR / "job_descriptions"
RESUME_DIR = DATA_DIR / "resume"
METADATA_PATH = DATA_DIR / "jd_metadata.csv"

# Load metadata CSV
jd_metadata = pd.read_csv(METADATA_PATH)

# Preview metadata
print("JD metadata loaded successfully.")
print("Number of rows in metadata:", len(jd_metadata))

display(jd_metadata.head(10))

JD metadata loaded successfully.
Number of rows in metadata: 10

,filename,company,title,source_url,date_collected
0,jd_01_sales_operations_analyst.txt,JM Eagle,Sales Operations Analyst,https://www.linkedin.com/jobs/view/4405059025,5/12/26
1,jd_02_revenue_operations_associate.txt,Sunbit,Revenue Operations Associate,https://www.linkedin.com/jobs/view/4406226503,5/12/26
2,jd_03_crm_operations_associate.txt,FanDuel,CRM Operations Associate,https://www.linkedin.com/jobs/view/4361065784,5/12/26
3,jd_04_gtm_operations_manager.txt,Cast & Crew,GTM Operations Manager,https://www.linkedin.com/jobs/view/4407973056,5/12/26
4,jd_05_business_analyst.txt,Salted,Business Analyst,https://www.linkedin.com/jobs/view/4387786174,5/12/26
5,jd_06_data_analyst.txt,Skechers,Operations Data & Financial Analyst,https://www.linkedin.com/jobs/view/4408048076,5/12/26
6,jd_07_business_intelligence_analyst.txt,Greater Good Health,Business Intelligence Analyst,https://www.linkedin.com/jobs/view/4410229599,5/12/26
7,jd_08_operations_analyst.txt,Masimo,Operations Analyst,https://www.linkedin.com/jobs/view/4378611641,5/12/26
8,jd_09_strategy_analyst.txt,Curana Health,"Business Analyst, Strategic Operations",https://www.linkedin.com/jobs/view/4407798544,5/12/26
9,jd_10_associate_consultant_operations.txt,O Positiv Health,Associate Strategy Manager,https://www.linkedin.com/jobs/view/4399497055,5/12/26

In [33]:
# ── Load JD documents and resume ──

jd_documents = []
resume_documents = []

# Load job description text files
for _, row in jd_metadata.iterrows():
    filename = row["filename"]
    file_path = JD_DIR / filename
    
    if file_path.exists():
        text = file_path.read_text(encoding="utf-8")
        
        doc = Document(
            page_content=text,
            metadata={
                "doc_type": "job_description",
                "filename": filename,
                "company": row["company"],
                "title": row["title"],
                "source_url": row["source_url"],
                "date_collected": row["date_collected"]
            }
        )
        
        jd_documents.append(doc)
    
    else:
        print(f"Missing file: {file_path}")

# Load resume text file
resume_files = list(RESUME_DIR.glob("*.txt"))

if len(resume_files) == 0:
    print("No resume .txt file found in data/resume/")
else:
    resume_path = resume_files[0]
    resume_text = resume_path.read_text(encoding="utf-8")
    
    resume_doc = Document(
        page_content=resume_text,
        metadata={
            "doc_type": "resume",
            "filename": resume_path.name
        }
    )
    
    resume_documents.append(resume_doc)

print("Job descriptions loaded:", len(jd_documents))
print("Resume documents loaded:", len(resume_documents))

Job descriptions loaded: 10
Resume documents loaded: 1

In [35]:
# ── Preview sample content ──

print("=== Sample Job Description ===")
print("Company:", jd_documents[0].metadata["company"])
print("Title:", jd_documents[0].metadata["title"])
print("Filename:", jd_documents[0].metadata["filename"])
print()
print(jd_documents[0].page_content[:1000])

print("\n" + "=" * 80 + "\n")

print("=== Resume Preview ===")
print("Filename:", resume_documents[0].metadata["filename"])
print()
print(resume_documents[0].page_content[:1000])

=== Sample Job Description ===
Company: JM Eagle
Title: Sales Operations Analyst
Filename: jd_01_sales_operations_analyst.txt

Sales Operations Analyst
JM Eagle

About the job
SUMMARY
Reporting daily to the company headquarters in Los Angeles, the Sales Operations Analyst role is will be responsible for processing multiple purchase orders (POs), coordinating deliveries, managing product sourcing, and ensuring seamless operational processes. This role requires exceptional detail orientation, optimal organization, strong technical skills, outstanding customer service abilities, and a commitment to accuracy in a fast-paced environment.

WORK LOCATION
Onsite. 5200 W. Century Blvd. Los Angeles, Ca. 90045

ESSENTIAL DUTIES AND RESPONSIBILITIES include the following. Other duties may be assigned.
Purchase Order Management: Process multiple purchase orders accurately and efficiently, adhering to company policies and timelines, and ensuring the highest level of service possible under the guidance of the Company’s Sales SOP.
Product Sourcing & Coordination: Collaborate with manufacturing plants and internal teams to sou

================================================================================

=== Resume Preview ===
Filename: resume.txt

Brandon Acosta

EDUCATION
Loyola Marymount University | Los Angeles, CA	May 2026
Master of Science in Business Analytics (STEM)
Honors: LMU Merit Scholarship | Program Senator, CBAGSA

University of California, Irvine | Irvine, CA	March 2023
Bachelor of Arts in Business Administration
Specializations: Operations & Decision Technologies, Marketing


EXPERIENCE
EndyMed Medical, Inc. (medical device manufacturer) | Remote	February 2025  - Present
Sales Operations Manager
Oversee order processing through Priority ERP, including order entry, major sales approvals, invoicing after shipment, and technical automations to the 3PL platform, ensuring compliance with medical device standards for quality assurance.
Manage warehouse inventory by performing quarterly reviews and leading projects to reduce inventory holding costs by 25%, such as excess loaner removal and discontinuation of old SKUs.
Ensure Shopify automations for DTC store run smoothly, including inventory sync, order fulfillment no

---
<a id="3-chunking"></a>
## 3. Text Chunking

Split your documents into chunks.  
**Required:** Try at least 2 chunking strategies, compare them quantitatively, and justify your final choice.

**Hint:** JDs often have natural sections (Requirements, Responsibilities, Qualifications). Consider whether your splitter respects these boundaries.

In [37]:
# ── Strategy 1 ──

# Strategy 1: Larger recursive chunks
# This keeps more surrounding context together, but may mix multiple JD sections in one chunk.

strategy_1_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    separators=["\n\n", "\n", ". ", " ", ""]
)

all_documents = jd_documents + resume_documents

strategy_1_chunks = strategy_1_splitter.split_documents(all_documents)

print("Strategy 1 complete.")
print("Total documents before chunking:", len(all_documents))
print("Total chunks created:", len(strategy_1_chunks))

# Count chunks by document type
strategy_1_counts = {}

for chunk in strategy_1_chunks:
    doc_type = chunk.metadata.get("doc_type", "unknown")
    
    if doc_type not in strategy_1_counts:
        strategy_1_counts[doc_type] = 0
    
    strategy_1_counts[doc_type] += 1

print("Chunks by document type:")
print(strategy_1_counts)

# Preview one chunk
print("\nSample chunk preview:")
print(strategy_1_chunks[0].page_content[:1000])

Strategy 1 complete.
Total documents before chunking: 11
Total chunks created: 83
Chunks by document type:
{'job_description': 77, 'resume': 6}

Sample chunk preview:
Sales Operations Analyst
JM Eagle

About the job
SUMMARY
Reporting daily to the company headquarters in Los Angeles, the Sales Operations Analyst role is will be responsible for processing multiple purchase orders (POs), coordinating deliveries, managing product sourcing, and ensuring seamless operational processes. This role requires exceptional detail orientation, optimal organization, strong technical skills, outstanding customer service abilities, and a commitment to accuracy in a fast-paced environment.

WORK LOCATION
Onsite. 5200 W. Century Blvd. Los Angeles, Ca. 90045

In [39]:
# ── Strategy 2 ──

# Strategy 2: Smaller section-aware recursive chunks
# This is designed for job descriptions because JDs often have sections like:
# Responsibilities, Qualifications, Requirements, Skills, and Preferred Qualifications.

strategy_2_splitter = RecursiveCharacterTextSplitter(
    chunk_size=600,
    chunk_overlap=100,
    separators=[
        "\n\nResponsibilities",
        "\n\nQualifications",
        "\n\nRequirements",
        "\n\nPreferred Qualifications",
        "\n\nSkills",
        "\n\nAbout",
        "\n\n",
        "\n",
        ". ",
        " ",
        ""
    ]
)

strategy_2_chunks = strategy_2_splitter.split_documents(all_documents)

print("Strategy 2 complete.")
print("Total documents before chunking:", len(all_documents))
print("Total chunks created:", len(strategy_2_chunks))

# Count chunks by document type
strategy_2_counts = {}

for chunk in strategy_2_chunks:
    doc_type = chunk.metadata.get("doc_type", "unknown")
    
    if doc_type not in strategy_2_counts:
        strategy_2_counts[doc_type] = 0
    
    strategy_2_counts[doc_type] += 1

print("Chunks by document type:")
print(strategy_2_counts)

# Preview one chunk
print("\nSample chunk preview:")
print(strategy_2_chunks[0].page_content[:1000])

Strategy 2 complete.
Total documents before chunking: 11
Total chunks created: 139
Chunks by document type:
{'job_description': 131, 'resume': 8}

Sample chunk preview:
Sales Operations Analyst
JM Eagle

In [43]:
# ── Compare strategies ──

def summarize_chunks(chunks, strategy_name):
    chunk_lengths = [len(chunk.page_content) for chunk in chunks]
    
    summary = {
        "strategy": strategy_name,
        "total_chunks": len(chunks),
        "avg_chunk_length": round(sum(chunk_lengths) / len(chunk_lengths), 2),
        "min_chunk_length": min(chunk_lengths),
        "max_chunk_length": max(chunk_lengths),
        "jd_chunks": sum(1 for chunk in chunks if chunk.metadata.get("doc_type") == "job_description"),
        "resume_chunks": sum(1 for chunk in chunks if chunk.metadata.get("doc_type") == "resume")
    }
    
    return summary

chunking_comparison = pd.DataFrame([
    summarize_chunks(strategy_1_chunks, "Strategy 1: Larger recursive chunks"),
    summarize_chunks(strategy_2_chunks, "Strategy 2: Smaller section-aware chunks")
])

display(chunking_comparison)

,strategy,total_chunks,avg_chunk_length,min_chunk_length,max_chunk_length,jd_chunks,resume_chunks
0,Strategy 1: Larger recursive chunks,83,720.89,54,990,77,6
1,Strategy 2: Smaller section-aware chunks,139,421.27,14,600,131,8

### Chunking Decision

**Which strategy did you choose?**  I selected Strategy 2 as the final chunking approach. 

**Why?**  Streagy 2 used smaller, section-aware recursive chunks with a chunk size of 600 and an overlap of 100. This strategy is better suited for job descriptions because many postings are organized into sections such as responsibilities, qualifications, requirements, preferred qualifications, and skills. Smaller chunks make retrieval more focused and easier to compare with evidence from the resume. Precise skill gaps, keyword alignment, and fit summary analysis are all stronger with improved and more specific chunking. 

**Final settings (chunk_size, overlap):** Smaller section-aware chunks, max_chunk_length = 600, overlap = 100

---
<a id="4-embedding"></a>
## 4. Embedding and Vector Store

Embed your chunks and store them in a vector database (ChromaDB or FAISS).

**Paid path:** OpenAI `text-embedding-3-small`  
**Free path:** `sentence-transformers/all-MiniLM-L6-v2`

After creating the store, run a test similarity search to verify it works.

In [46]:
# ── Create embeddings and vector store ──

# Create OpenAI embedding model
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small",
    api_key=openai_api_key
)

# Optional: define a persistent ChromaDB folder
CHROMA_DIR = "chroma_db"

# Create Chroma vector store from final selected chunks
vector_store = Chroma.from_documents(
    documents=final_chunks,
    embedding=embeddings,
    persist_directory=CHROMA_DIR
)

print("Vector store created successfully.")
print("Embedding model: text-embedding-3-small")
print("Number of chunks stored:", len(final_chunks))
print("Persist directory:", CHROMA_DIR)

Vector store created successfully.
Embedding model: text-embedding-3-small
Number of chunks stored: 139
Persist directory: chroma_db

In [48]:
# ── Verify: run a test similarity search ──

test_query = "sales operations crm reporting dashboard analytics"

search_results = vector_store.similarity_search(
    query=test_query,
    k=5
)

print("Similarity search completed successfully.")
print("Query:", test_query)
print("Number of results returned:", len(search_results))

for i, result in enumerate(search_results, start=1):
    print("\n" + "=" * 80)
    print(f"Result {i}")
    print("Document type:", result.metadata.get("doc_type"))
    print("Filename:", result.metadata.get("filename"))
    
    if result.metadata.get("doc_type") == "job_description":
        print("Company:", result.metadata.get("company"))
        print("Title:", result.metadata.get("title"))
    
    print("\nContent preview:")
    print(result.page_content[:700])

Similarity search completed successfully.
Query: sales operations crm reporting dashboard analytics
Number of results returned: 5

================================================================================
Result 1
Document type: resume
Filename: resume.txt

Content preview:
Standardized CRM tools for B2B sales teams, creating automated deal pipelines, email nurture sequences, and a KPI dashboard for managerial insights and individual contributor activity tracking.

================================================================================
Result 2
Document type: job_description
Filename: jd_04_gtm_operations_manager.txt
Company: Cast & Crew
Title: GTM Operations Manager

Content preview:
Ensure alignment between marketing-generated pipeline and sales outcomes
Integrate marketing data into CRM for end-to-end reporting

Customer Lifecycle Visibility (Pre and Post Sale)
Build end-to-end dashboards across the customer journey: new, onboarding, adoption, expansion, and renewal
Track and report on retention, churn, expansion, and customer health
Partner with Sales and Customer Success to identify at-risk accounts

Operating Cadence and QBR Infrastructure
Build and run pipeline reviews and forecast calls
Standardize QBRs and performance reporting across business units

================================================================================
Result 3
Document type: job_description
Filename: jd_04_gtm_operations_manager.txt
Company: Cast & Crew
Title: GTM Operations Manager

Content preview:
Role Overview
This role is the operating backbone of the commercial organization.
Reporting to the Chief Revenue Officer, you will bring structure, visibility, and discipline to pipeline management, forecasting, and full customer lifecycle performance. You will own HubSpot and lead CRM consolidation, while building the dashboards and operating cadence required to create a predictable, scalable revenue engine.
This is a hands-on role for a systems thinker who can translate data into action and drive alignment across Marketing, Sales, and Customer Success.


Core Responsibilities

================================================================================
Result 4
Document type: job_description
Filename: jd_04_gtm_operations_manager.txt
Company: Cast & Crew
Title: GTM Operations Manager

Content preview:
Pipeline, Forecasting, and KPI Discipline
Own pipeline visibility, hygiene, and inspection cadence
Build and maintain KPI dashboards across full funnel performance, including lead conversion, pipeline, velocity, and forecast accuracy
Establish and enforce forecasting methodology and reporting standards
Identify risks early and provide clear, actionable insights to leadership

CRM Ownership and Transformation (HubSpot)
Own HubSpot configuration, governance, and adoption

================================================================================
Result 5
Document type: job_description
Filename: jd_04_gtm_operations_manager.txt
Company: Cast & Crew
Title: GTM Operations Manager

Content preview:
Align workflows across Marketing, Sales, and Customer Success

Key Qualifications
5–8 years in Sales Operations, Revenue Operations, or GTM Strategy
Deep, hands-on experience with HubSpot (required)
Proven ability to build forecasting discipline and pipeline inspection frameworks
Strong analytical skills with the ability to translate data into business insight
Experience supporting senior leadership with executive-level reporting
Track record of driving CRM adoption and improving data integrity
Experience working across Marketing, Sales, and Customer Success data models

---
<a id="5-analysis"></a>
## 5. Analysis Prompts and Chain

Build 3 analysis types, each with its own prompt:

1. **Skill Gap Report:** Compare resume skills vs. JD requirements. Output matching skills, missing skills, and recommended actions.
2. **Keyword Alignment:** Extract key terms from a JD, check which appear in the resume, report a match rate.
3. **Fit Summary:** 3-4 sentence narrative assessment citing evidence from both documents.

You also need to wire up the LLM and a way to pass a specific JD + resume into each prompt.

**Required:** Document at least 3 prompt iterations total (across any analysis type) with rationale.

**Reminder:** Prompt design must be your own work (Tier 2 — AI prohibited for this step).

In [50]:
# ── Initialize LLM ──

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
    api_key=openai_api_key
)

print("LLM initialized successfully.")
print("Model: gpt-4o-mini")
print("Temperature: 0")

LLM initialized successfully.
Model: gpt-4o-mini
Temperature: 0

In [58]:
# ── Analysis 1: Skill Gap Report ──
# — Analysis 1: Skill Gap Report —

# Choose one JD to test
selected_jd_filename = "jd_01_sales_operations_analyst.txt"

def get_jd_context(filename, query, k=5):
    """
    Retrieve relevant chunks from one selected job description.
    """
    results = vector_store.similarity_search(
        query=query,
        k=k,
        filter={
            "filename": filename
        }
    )
    
    return "\n\n".join([doc.page_content for doc in results])


def get_resume_context(query, k=5):
    """
    Retrieve relevant chunks from the resume.
    """
    results = vector_store.similarity_search(
        query=query,
        k=k,
        filter={
            "doc_type": "resume"
        }
    )
    
    return "\n\n".join([doc.page_content for doc in results])


skill_gap_jd_context = get_jd_context(
    filename=selected_jd_filename,
    query="required skills qualifications responsibilities experience tools",
    k=5
)

skill_gap_resume_context = get_resume_context(
    query="skills experience projects tools education responsibilities",
    k=5
)

skill_gap_prompt_text = """
Pretend you are a recruiter reviewing job applications using a resume and job description. You are being provided the job description text file and resume text file. Please compare the job description's requirements with the resume's skill section. 

Your output must include (1) a list of matching skills, (2) a list of missing skills, and (3) recommended actions to close the skill gap. 

You must only use the provided inputs. Do not hallucinate experience, make assumptions, or make changes to the input files.

Job Description: {job_description}
Resume: {resume}
"""

skill_gap_prompt = PromptTemplate(
    input_variables=["job_description", "resume"],
    template=skill_gap_prompt_text
)

skill_gap_chain = skill_gap_prompt | llm | StrOutputParser()

skill_gap_result = skill_gap_chain.invoke({
    "job_description": skill_gap_jd_context,
    "resume": skill_gap_resume_context
})

print(skill_gap_result)

### Matching Skills
1. **Order & Inventory Management**: The resume mentions "Order Processing" and "Inventory Control," which aligns with the job description's emphasis on "Purchase Order Management" and "Inventory Management."
2. **E-Commerce & CRM**: The resume lists experience with various CRM systems (e.g., Monday CRM, HubSpot, PipeDrive), which matches the job description's requirement for proficiency in CRM systems.
3. **Analytics**: The resume indicates proficiency in Excel, which is required in the job description.
4. **Customer Service**: The resume highlights "Customer Success" and experience in managing customer interactions, aligning with the job description's focus on providing excellent customer service.
5. **Process Improvement**: The resume mentions "Process Improvement," which corresponds to the job description's emphasis on "Process Optimization."

### Missing Skills
1. **Proficiency in AS 400**: The resume does not mention experience with AS 400, which is specified in the job description.
2. **Strong Attention to Detail**: While the resume implies attention to detail through various roles, it does not explicitly state this skill.
3. **Excellent Organizational Skills**: The resume does not explicitly mention organizational skills, which are highlighted in the job description.
4. **Effective Communication and Interpersonal Skills**: Although the resume implies some level of communication skills through customer success roles, it does not explicitly state effective communication and interpersonal skills.
5. **Problem-Solving Skills**: The resume does not explicitly mention problem-solving skills, which are required in the job description.

### Recommended Actions to Close the Skill Gap
1. **Gain Experience with AS 400**: Consider taking a course or seeking out resources to learn about AS 400 systems, as this is a specific requirement in the job description.
2. **Highlight Attention to Detail**: Update the resume to include specific examples or statements that demonstrate attention to detail in previous roles.
3. **Emphasize Organizational Skills**: Include examples of how organizational skills were utilized in past positions, such as managing multiple projects or tasks simultaneously.
4. **Develop Communication Skills**: Engage in activities that enhance communication skills, such as public speaking courses or team collaboration projects, and update the resume to reflect these experiences.
5. **Showcase Problem-Solving Skills**: Include specific instances in the resume where problem-solving was applied, such as overcoming challenges in order processing or inventory management.

In [69]:
# ── Analysis 2: Keyword Alignment ──

keyword_jd_context = get_jd_context(
    filename=selected_jd_filename,
    query="keywords tools technologies qualifications required skills preferred skills",
    k=5
)

keyword_resume_context = get_resume_context(
    query="skills tools technologies software platforms certifications projects experience",
    k=5
)

keyword_alignment_prompt_text = """
Pretend you are a recruiter reviewing resumes to match them to a job description. You are being provided with the job description and resume contexts for review. 

Job Description: {job_description}
Resume: {resume}

Your output will be a table. Column1 of the table will be a list of keywords or phrases directly from the job description. These should be justified, specific, and not repeated. Keep them brief, big-picture keywords from the job description. 

Column 2 will indicate whether each keyword matches the provided resume. If each keyword directly matches the resume, it is a match. If not, it is missing, or requires expansion. This is a Match/No Match result.

Column 3 should serve as your justification from the resume for the match, to ensure that it is proper. For any slight matches, you can include your justification for decision in this column as well. Keep your reasoning concise. 
Below the table, provide a final match rate for the keywords between the job description and resume. 

Do not hallucinate any keywords or skills from either the job description or resume; you are only limited to those. Do not make assumptions. 
"""

keyword_alignment_prompt = PromptTemplate(
    input_variables=["job_description", "resume"],
    template=keyword_alignment_prompt_text
)

keyword_alignment_chain = keyword_alignment_prompt | llm | StrOutputParser()

keyword_alignment_result = keyword_alignment_chain.invoke({
    "job_description": keyword_jd_context,
    "resume": keyword_resume_context
})

print(keyword_alignment_result)

| **Keywords/Phrases**                          | **Match/No Match** | **Justification**                                                                                     |
|-----------------------------------------------|---------------------|-------------------------------------------------------------------------------------------------------|
| Customer Service in manufacturing environment  | No Match            | The resume does not explicitly mention customer service experience in a manufacturing environment.    |
| Recent college graduates or early-career professionals | No Match            | The resume does not indicate the candidate is a recent graduate or early-career professional.          |
| Proficiency in Microsoft Excel, Word, AS 400, and/or CRM systems | Match               | The resume lists proficiency in Excel and various CRM systems (Monday CRM, HubSpot, PipeDrive).       |
| Strong attention to detail                     | No Match            | The resume does not explicitly mention attention to detail, though it implies it through process improvement. |
| Excellent organizational skills                | No Match            | The resume does not specifically mention organizational skills, though it implies project management.  |
| Effective communication and interpersonal skills | Match               | The resume indicates experience in customer success and collaboration with sales teams, suggesting strong communication skills. |
| Problem-solving skills                         | Match               | The resume mentions process improvement and automation, indicating problem-solving capabilities.       |
| Prior experience in purchase order processing  | Match               | The resume includes experience in order processing through Priority ERP and managing inventory.       |
| Bachelor's Degree in Business or related field | No Match            | The resume does not mention the candidate's educational background.                                   |
| System Proficiency                             | Match               | The resume lists proficiency in various systems including Excel, multiple CRMs, and ERP systems.     |
| Process Optimization                           | Match               | The resume mentions leading projects to reduce inventory holding costs and automating processes.      |
| Customer Service                               | Match               | The resume indicates experience in customer success and post-sales support, which relates to customer service. |
| Inventory Management                           | Match               | The resume includes managing warehouse inventory and performing quarterly reviews.                     |
| Communication with customers and sales personnel | Match               | The resume states experience in supporting sales teams and communicating with customers.              |
| Product Knowledge                              | No Match            | The resume does not mention obtaining product knowledge or attending technical training seminars.      |

**Final Match Rate:** 10 out of 15 keywords matched, resulting in a match rate of 66.67%.

In [71]:
# ── Analysis 3: Fit Summary ──

fit_jd_context = get_jd_context(
    filename=selected_jd_filename,
    query="role responsibilities qualifications required experience preferred qualifications",
    k=5
)

fit_resume_context = get_resume_context(
    query="professional experience education skills projects achievements tools",
    k=5
)

fit_summary_prompt_text = """
Pretend you are a recruiter reviewing resumes and matching them against the job description for a job posting. You are being provided the resume context and job description context. 

Job Description: {job_description} 
Resume: {resume} 

Do a comprehensive analysis of the keywords, experience requirements, and desired skill sets in the job description. Match this against the provided resume. 

Write a short 3-4 sentence narrative assessment of the job fit, make sure it is no longer than 4 sentences. 

Make sure to cite evidence from both the job description and resume. Do not make hallucinations, assumptions from the resume, or exaggerate the fit. Make sure there is no bias. 
"""

fit_summary_prompt = PromptTemplate(
    input_variables=["job_description", "resume"],
    template=fit_summary_prompt_text
)

fit_summary_chain = fit_summary_prompt | llm | StrOutputParser()

fit_summary_result = fit_summary_chain.invoke({
    "job_description": fit_jd_context,
    "resume": fit_resume_context
})

print(fit_summary_result)

The candidate's experience as a Sales Operations Manager at EndyMed Medical, Inc. aligns well with the job description's emphasis on order processing and customer service in a manufacturing environment, as they have overseen order processing and ensured compliance with quality standards. Their proficiency in Microsoft Excel, as evidenced by their use of Power Query and PivotTables, meets the requirement for strong Excel skills. Additionally, their role in automating processes and managing inventory demonstrates strong attention to detail and organizational skills, which are crucial for managing multiple tasks simultaneously. Overall, the candidate possesses relevant experience and skills that match the qualifications outlined in the job description.

### Prompt Iteration Log

Document at least 3 total iterations across any of the analysis types.

**Iteration 1:** For the second analysis, the first prompt worked very strongly: 

_Pretend you are a recruiter reviewing resumes to match to a job description for a job posting. You are being provided the job description context and resume context for review._

_Job Description: {job_description}
Resume: {resume}_

_Please start by creating a table of keywords from the job description for your output. Then, compare each keyword to the resume provided, and rank whether or not they are matched._

_The structure of the table will be column1= Keyword from JD, column2= match rating to resume, and column3= evidence to verify match for those that matched._

_Finalize your output with a match percentage for the resume and job description for evaluation of strength for application._

However, the output ranked each match as "Strong", "Moderate", or "Weak", which is objective but does not provide sufficient analysis. Additionally, the prompt is missing the prevention of hallucination. Finally, the calculation for the match percentage is explained, but it's not necessary. The output just needs to provide a match percentage. 

**Iteration 2:** For the second analysis, the second prompt made significant improvements from the previous iteration:

_Pretend you are a recruiter reviewing resumes to match them to a job description. You are being provided with the job description and resume contexts for review._

_Job Description: {job_description}
Resume: {resume}_

_Your output will be a table. Column1 of the table will be a list of keywords or phrases directly from the job description. These should be justified, specific, and not repeated. Keep them brief, big-picture keywords from the job description._ 

_Column 2 will indicate whether each keyword matches the provided resume. If each keyword directly matches the resume, it is a match. If not, it is missing, or requires expansion. This is a Match/No Match result._

_Column 3 should serve as your justification from the resume for the match, to ensure that it is proper. For any slight matches, you can include your justification for decision in this column as well. Keep your reasoning concise._ 

_Below the table, provide a final match rate for the keywords between the job description and resume._ 

_Do not hallucinate any keywords or skills from either the job description or resume; you are only limited to those. Do not make assumptions._ 

This prompt helped simplify the output by specifically requesting concise reasoning and development of the keywords/phrases list. Furthermore, this prompt removes the potential for any hallucinations or assumptions. It also uses more concise language to justify the match and restricts the model to a binary selection between Match and No Match. Furthermore, it removes the complicated calculation of the match score, and instead, just totals up the number of matches and no matches. 

**Iteration 3:** For the third analysis, the second iteration of the prompt was significantly more optimized: 

_Pretend you are a recruiter reviewing resumes and matching them against the job description for a job posting. You are being provided the resume context and job description context._

_Job Description: {job_description} 
Resume: {resume}_

_Do a comprehensive analysis of the keywords, experience requirements, and desired skill sets in the job description. Match this against the provided resume._

_Write a short 3-4 sentence narrative assessment of the job fit, make sure it is no longer than 4 sentences._ 

_Make sure to cite evidence from both the job description and resume. Do not make hallucinations, assumptions from the resume, or exaggerate the fit. Make sure there is no bias._ 

The original prompt lacked a specific request for evidence to justify the job fit. Asking it to cite specific evidence helps ensure that no misrepresentations, assumptions, or exaggerations are made. The model is also restricted by a specific request to prevent hallucinations. Because this is a broader prompt, asking it to be concise and evidence-based helps prevent mistakes.

---
<a id="6-comparison"></a>
## 6. Zero-shot vs. Few-shot Comparison

Pick one of your 3 analysis types. Create a few-shot version by adding 1-2 example input/output pairs to the prompt. Run both versions on the same JD and compare outputs.

**Reminder:** You must write the few-shot examples yourself (Tier 2).

In [77]:
# ── Few-shot version of your chosen analysis ──

# We are comparing the Skill Gap Report prompt from Step 5
# using the same selected JD and resume contexts.

few_shot_skill_gap_prompt_text = """
You are comparing a candidate's resume against a job description.

Use only the provided job description and resume. Do not make assumptions, exaggerations, or hallucinations.

Example 1:

Job Description:
The role requires SQL, dashboard development, stakeholder reporting, and experience translating business needs into analytics deliverables. This is for a Business Analyst role. 

Resume:
The candidate has built Tableau dashboards, used SQL for data extraction, and presented weekly KPI reporting to business stakeholders.

Your output must include (1) a list of matching skills, (2) a list of missing skills, and (3) recommended actions to close the skill gap. 

Example 2:

Job Description:
The role requires experience with Python, machine learning model evaluation, A/B testing, and cloud deployment. This is for a Marketing Analytics role.

Resume:
The candidate has Python coursework, built classification models in Jupyter Notebook, and evaluated models using accuracy and confusion matrices.

Your output must include (1) a list of matching skills, (2) a list of missing skills, and (3) recommended actions to close the skill gap. 

Job Description Context:
{job_description}

Resume Context:
{resume}
"""

few_shot_skill_gap_prompt = PromptTemplate(
    input_variables=["job_description", "resume"],
    template=few_shot_skill_gap_prompt_text
)

few_shot_skill_gap_chain = few_shot_skill_gap_prompt | llm | StrOutputParser()

few_shot_skill_gap_result = few_shot_skill_gap_chain.invoke({
    "job_description": skill_gap_jd_context,
    "resume": skill_gap_resume_context
})

print(few_shot_skill_gap_result)

### Matching Skills:
1. **Order & Inventory Management**: Experience in order processing and inventory control.
2. **Customer Service**: Developed consistent customer experiences and provided support to internal and external stakeholders.
3. **Proficiency in Microsoft Excel**: Utilized Excel for analytics and data management.
4. **Organizational Skills**: Managed multiple tasks simultaneously in various roles.
5. **Problem-Solving Skills**: Implemented process improvements and automated systems to enhance efficiency.

### Missing Skills:
1. **Experience with AS 400**: No mention of familiarity with AS 400 systems.
2. **Experience with CRM systems**: While the candidate has experience with various CRM platforms, specific mention of AS 400 or similar systems is lacking.
3. **Specific Experience in Purchase Order Processing**: While the candidate has relevant experience, the job description emphasizes prior experience in purchase order processing as preferred.
4. **Strong Attention to Detail**: While implied through experience, there is no explicit mention of attention to detail in complex operational environments.

### Recommended Actions to Close the Skill Gap:
1. **Gain Familiarity with AS 400**: The candidate should seek training or online courses to become proficient in AS 400 systems, which may be beneficial for the role.
2. **Highlight Relevant CRM Experience**: The candidate should emphasize their experience with CRM systems in the resume, particularly how it relates to customer service and order management.
3. **Detail Purchase Order Processing Experience**: The candidate should provide more specific examples of their experience with purchase order processing in their resume to align with the job description.
4. **Demonstrate Attention to Detail**: The candidate could include specific examples or metrics that showcase their attention to detail in previous roles, particularly in complex operational tasks.

In [78]:
# ── Run both on the same JD, display side by side ──

# Re-run zero-shot skill gap result on the same JD/resume context
zero_shot_skill_gap_result = skill_gap_chain.invoke({
    "job_description": skill_gap_jd_context,
    "resume": skill_gap_resume_context
})

# Store comparison in a dataframe for side-by-side review
zero_vs_few_shot_comparison = pd.DataFrame({
    "Prompt Type": ["Zero-shot", "Few-shot"],
    "Analysis Type": ["Skill Gap Report", "Skill Gap Report"],
    "Selected JD": [selected_jd_filename, selected_jd_filename],
    "Output": [zero_shot_skill_gap_result, few_shot_skill_gap_result]
})

display(zero_vs_few_shot_comparison)

print("=== ZERO-SHOT OUTPUT ===")
print(zero_shot_skill_gap_result)

print("\n" + "=" * 100 + "\n")

print("=== FEW-SHOT OUTPUT ===")
print(few_shot_skill_gap_result)

,Prompt Type,Analysis Type,Selected JD,Output
0,Zero-shot,Skill Gap Report,jd_01_sales_operations_analyst.txt,### Matching Skills\n1. **Order Management**: ...
1,Few-shot,Skill Gap Report,jd_01_sales_operations_analyst.txt,### Matching Skills:\n1. **Order & Inventory M...

=== ZERO-SHOT OUTPUT ===
### Matching Skills
1. **Order Management**: Experience in order processing and management through various systems (Priority ERP, Shopify).
2. **Inventory Management**: Skills in managing and controlling inventory levels.
3. **Customer Service**: Experience in providing support and ensuring customer satisfaction.
4. **Proficiency in Microsoft Excel**: Mentioned in the resume under analytics.
5. **Organizational Skills**: Demonstrated through managing multiple tasks and projects in previous roles.

### Missing Skills
1. **Experience in a manufacturing environment**: The resume does not explicitly mention experience in a manufacturing setting, although it does include experience in medical device companies.
2. **Proficiency in AS 400**: Not mentioned in the resume.
3. **Experience with CRM systems specifically mentioned in the job description**: While the resume lists CRM tools, it does not mention AS 400 or the specific CRM systems listed in the job description.
4. **Problem-solving skills related to sourcing, deliveries, or order discrepancies**: While there are examples of process improvement, specific problem-solving related to sourcing and deliveries is not highlighted.
5. **Bachelor's Degree in Business or related field**: The resume does not provide educational qualifications.

### Recommended Actions to Close the Skill Gap
1. **Gain Experience in a Manufacturing Environment**: Seek internships or entry-level positions in manufacturing settings to gain relevant experience.
2. **Learn AS 400**: Consider taking online courses or tutorials to become proficient in AS 400, as it is a specific requirement in the job description.
3. **Highlight Relevant CRM Experience**: If applicable, provide more details on experience with CRM systems that align with those mentioned in the job description (e.g., AS 400).
4. **Develop Problem-Solving Skills**: Engage in projects or training that focus on problem-solving in logistics and supply chain management to better align with the job requirements.
5. **Obtain a Bachelor's Degree**: If not already completed, consider pursuing a degree in Business or a related field to meet the educational qualifications specified in the job description. If already obtained, ensure it is clearly stated on the resume.

====================================================================================================

=== FEW-SHOT OUTPUT ===
### Matching Skills:
1. **Order & Inventory Management**: Experience in order processing and inventory control.
2. **Customer Service**: Developed consistent customer experiences and provided support to internal and external stakeholders.
3. **Proficiency in Microsoft Excel**: Utilized Excel for analytics and data management.
4. **Organizational Skills**: Managed multiple tasks simultaneously in various roles.
5. **Problem-Solving Skills**: Implemented process improvements and automated systems to enhance efficiency.

### Missing Skills:
1. **Experience with AS 400**: No mention of familiarity with AS 400 systems.
2. **Experience with CRM systems**: While the candidate has experience with various CRM platforms, specific mention of AS 400 or similar systems is lacking.
3. **Specific Experience in Purchase Order Processing**: While the candidate has relevant experience, the job description emphasizes prior experience in purchase order processing as preferred.
4. **Strong Attention to Detail**: While implied through experience, there is no explicit mention of attention to detail in complex operational environments.

### Recommended Actions to Close the Skill Gap:
1. **Gain Familiarity with AS 400**: The candidate should seek training or online courses to become proficient in AS 400 systems, which may be beneficial for the role.
2. **Highlight Relevant CRM Experience**: The candidate should emphasize their experience with CRM systems in the resume, particularly how it relates to customer service and order management.
3. **Detail Purchase Order Processing Experience**: The candidate should provide more specific examples of their experience with purchase order processing in their resume to align with the job description.
4. **Demonstrate Attention to Detail**: The candidate could include specific examples or metrics that showcase their attention to detail in previous roles, particularly in complex operational tasks.

### Zero-shot vs. Few-shot Analysis

**Which analysis type did you compare?** The first analysis, Skill Gap Report.

**Which performed better?** The few-shot output.

**Why? (use specific examples from the outputs above)** The few-shot output is more specific and provides more useful recommendations for improving a candidate's resume, improving the match to the job description. The zero-shot had similar matching and recommendations; however, it made some pretty significant gaps. For example, it states that the candidate should get a Bachelor's degree as a recommendation, which is inaccurate. The few-shot output's recommendations are far more skill-specific. It addresses key elements of the skill gaps, like the AS 400, CRM experience, and order management processes of the job description. Another inaccuracy of the zero-shot output is the statement that the candidate should improve their "problem-solving skills", meaning that it missed those contextual elements of the resume. The zero-shot seems to prioritize direct mentions and matches, while the few-shot takes into account context, making its recommendations more solid.

---
<a id="7-evaluation"></a>
## 7. Evaluation

Run all 3 analysis types on your **top 3 target JDs** (9 total analyses).

For each, score:
- **Retrieval relevance:** Did it pull the right JD sections? (Yes/Partial/No)
- **Skill identification accuracy:** Are identified skills/gaps correct? (count correct vs. incorrect)
- **Actionability:** Are recommendations specific and useful? (1-5)
- **Faithfulness:** Does output stick to document content? (Faithful/Partial/Hallucinated)

**Reminder:** Evaluation must be your own work (Tier 2 — AI prohibited).

In [96]:
# Check metadata and loaded JD filenames side by side

print("Metadata filenames:")
print(jd_metadata["filename"].tolist())

print("\nLoaded JD document filenames:")
print([doc.metadata["filename"] for doc in jd_documents])

print("\nVector store test for each metadata filename:")

for filename in jd_metadata["filename"].tolist():
    test_results = vector_store.similarity_search(
        query="required skills qualifications responsibilities",
        k=3,
        filter={"filename": filename}
    )
    
    print(filename, "->", len(test_results), "chunks found")

Metadata filenames:
['jd_01_sales_operations_analyst.txt', 'jd_02_revenue_operations_associate.txt', 'jd_03_crm_operations_associate.txt', 'jd_04_gtm_operations_manager.txt', 'jd_05_business_analyst.txt', 'jd_06_data_analyst.txt', 'jd_07_business_intelligence_analyst.txt', 'jd_08_operations_analyst.txt', 'jd_09_strategy_analyst.txt', 'jd_10_associate_consultant_operations.txt']

Loaded JD document filenames:
['jd_01_sales_operations_analyst.txt', 'jd_02_revenue_operations_associate.txt', 'jd_03_crm_operations_associate.txt', 'jd_04_gtm_operations_manager.txt', 'jd_05_business_analyst.txt', 'jd_06_data_analyst.txt', 'jd_07_business_intelligence_analyst.txt', 'jd_08_operations_analyst.txt', 'jd_09_strategy_analyst.txt', 'jd_10_associate_consultant_operations.txt']

Vector store test for each metadata filename:
jd_01_sales_operations_analyst.txt -> 3 chunks found
jd_02_revenue_operations_associate.txt -> 3 chunks found
jd_03_crm_operations_associate.txt -> 3 chunks found
jd_04_gtm_operations_manager.txt -> 3 chunks found
jd_05_business_analyst.txt -> 3 chunks found
jd_06_data_analyst.txt -> 3 chunks found
jd_07_business_intelligence_analyst.txt -> 3 chunks found
jd_08_operations_analyst.txt -> 3 chunks found
jd_09_strategy_analyst.txt -> 3 chunks found
jd_10_associate_consultant_operations.txt -> 3 chunks found

In [98]:
# Select top 3 JDs directly from metadata to avoid filename mismatch

top_3_jds = jd_metadata["filename"].head(3).tolist()

print("Top 3 JDs selected:")
for filename in top_3_jds:
    print(filename)

Top 3 JDs selected:
jd_01_sales_operations_analyst.txt
jd_02_revenue_operations_associate.txt
jd_03_crm_operations_associate.txt

In [100]:
# — Run 9 analyses (3 JDs x 3 analysis types) —

top_3_rows = jd_metadata.head(3).copy()

analysis_outputs = []

for _, jd_row in top_3_rows.iterrows():
    
    jd_filename = jd_row["filename"]
    company = jd_row["company"]
    title = jd_row["title"]
    
    print(f"Running analyses for: {jd_filename}")
    
    # -----------------------------
    # 1. Skill Gap Report
    # -----------------------------
    skill_gap_jd_context = get_jd_context(
        filename=jd_filename,
        query="required skills qualifications responsibilities experience tools",
        k=5
    )
    
    skill_gap_resume_context = get_resume_context(
        query="skills experience projects tools education responsibilities",
        k=5
    )
    
    skill_gap_output = skill_gap_chain.invoke({
        "job_description": skill_gap_jd_context,
        "resume": skill_gap_resume_context
    })
    
    analysis_outputs.append({
        "jd_filename": jd_filename,
        "company": company,
        "title": title,
        "analysis_type": "Skill Gap Report",
        "jd_context_length": len(skill_gap_jd_context),
        "resume_context_length": len(skill_gap_resume_context),
        "output": skill_gap_output
    })
    
    # -----------------------------
    # 2. Keyword Alignment
    # -----------------------------
    keyword_jd_context = get_jd_context(
        filename=jd_filename,
        query="keywords tools technologies qualifications required skills preferred skills",
        k=5
    )
    
    keyword_resume_context = get_resume_context(
        query="skills tools technologies software platforms certifications projects experience",
        k=5
    )
    
    keyword_output = keyword_alignment_chain.invoke({
        "job_description": keyword_jd_context,
        "resume": keyword_resume_context
    })
    
    analysis_outputs.append({
        "jd_filename": jd_filename,
        "company": company,
        "title": title,
        "analysis_type": "Keyword Alignment",
        "jd_context_length": len(keyword_jd_context),
        "resume_context_length": len(keyword_resume_context),
        "output": keyword_output
    })
    
    # -----------------------------
    # 3. Fit Summary
    # -----------------------------
    fit_jd_context = get_jd_context(
        filename=jd_filename,
        query="role responsibilities qualifications required experience preferred qualifications",
        k=5
    )
    
    fit_resume_context = get_resume_context(
        query="professional experience education skills projects achievements tools",
        k=5
    )
    
    fit_output = fit_summary_chain.invoke({
        "job_description": fit_jd_context,
        "resume": fit_resume_context
    })
    
    analysis_outputs.append({
        "jd_filename": jd_filename,
        "company": company,
        "title": title,
        "analysis_type": "Fit Summary",
        "jd_context_length": len(fit_jd_context),
        "resume_context_length": len(fit_resume_context),
        "output": fit_output
    })

print("All analyses completed.")

analysis_outputs_df = pd.DataFrame(analysis_outputs)

display(analysis_outputs_df[[
    "jd_filename",
    "company",
    "title",
    "analysis_type",
    "jd_context_length",
    "resume_context_length"
]])

Running analyses for: jd_01_sales_operations_analyst.txt
Running analyses for: jd_02_revenue_operations_associate.txt
Running analyses for: jd_03_crm_operations_associate.txt
All analyses completed.

,jd_filename,company,title,analysis_type,jd_context_length,resume_context_length
0,jd_01_sales_operations_analyst.txt,JM Eagle,Sales Operations Analyst,Skill Gap Report,2381,2418
1,jd_01_sales_operations_analyst.txt,JM Eagle,Sales Operations Analyst,Keyword Alignment,2217,2161
2,jd_01_sales_operations_analyst.txt,JM Eagle,Sales Operations Analyst,Fit Summary,1920,2161
3,jd_02_revenue_operations_associate.txt,Sunbit,Revenue Operations Associate,Skill Gap Report,2340,2418
4,jd_02_revenue_operations_associate.txt,Sunbit,Revenue Operations Associate,Keyword Alignment,2340,2161
5,jd_02_revenue_operations_associate.txt,Sunbit,Revenue Operations Associate,Fit Summary,2387,2161
6,jd_03_crm_operations_associate.txt,FanDuel,CRM Operations Associate,Skill Gap Report,2661,2418
7,jd_03_crm_operations_associate.txt,FanDuel,CRM Operations Associate,Keyword Alignment,2125,2161
8,jd_03_crm_operations_associate.txt,FanDuel,CRM Operations Associate,Fit Summary,2208,2161

In [104]:
# — Summarize evaluation results —

# Create a compact summary table from the 9 analysis outputs
evaluation_review_df = analysis_outputs_df[[
    "jd_filename",
    "company",
    "title",
    "analysis_type",
    "jd_context_length",
    "resume_context_length",
    "output"
]].copy()

# Add output length as a quick quality/debugging signal
evaluation_review_df["output_length"] = evaluation_review_df["output"].apply(len)

# Add a short preview so the table is easier to scan
evaluation_review_df["output_preview"] = evaluation_review_df["output"].apply(
    lambda x: x[:300].replace("\n", " ") + "..." if len(x) > 300 else x.replace("\n", " ")
)

# Reorder columns for readability
evaluation_review_df = evaluation_review_df[[
    "jd_filename",
    "company",
    "title",
    "analysis_type",
    "jd_context_length",
    "resume_context_length",
    "output_length",
    "output_preview",
    "output"
]]

display(evaluation_review_df)

,jd_filename,company,title,analysis_type,jd_context_length,resume_context_length,output_length,output_preview,output
0,jd_01_sales_operations_analyst.txt,JM Eagle,Sales Operations Analyst,Skill Gap Report,2381,2418,2577,### Matching Skills 1. **Order & Inventory Man...,### Matching Skills\n1. **Order & Inventory Ma...
1,jd_01_sales_operations_analyst.txt,JM Eagle,Sales Operations Analyst,Keyword Alignment,2217,2161,3130,| **Keywords/Phrases** ...,| **Keywords/Phrases** ...
2,jd_01_sales_operations_analyst.txt,JM Eagle,Sales Operations Analyst,Fit Summary,1920,2161,735,The candidate's experience as a Sales Operatio...,The candidate's experience as a Sales Operatio...
3,jd_02_revenue_operations_associate.txt,Sunbit,Revenue Operations Associate,Skill Gap Report,2340,2418,2549,### Matching Skills 1. **Process Improvement**...,### Matching Skills\n1. **Process Improvement*...
4,jd_02_revenue_operations_associate.txt,Sunbit,Revenue Operations Associate,Keyword Alignment,2340,2161,4408,| **Keywords/Phrases** ...,| **Keywords/Phrases** ...
5,jd_02_revenue_operations_associate.txt,Sunbit,Revenue Operations Associate,Fit Summary,2387,2161,764,The candidate has relevant experience as a Sal...,The candidate has relevant experience as a Sal...
6,jd_03_crm_operations_associate.txt,FanDuel,CRM Operations Associate,Skill Gap Report,2661,2418,3049,### Matching Skills 1. **SQL** - The resume li...,### Matching Skills\n1. **SQL** - The resume l...
7,jd_03_crm_operations_associate.txt,FanDuel,CRM Operations Associate,Keyword Alignment,2125,2161,4827,| **Keywords/Phrases** ...,| **Keywords/Phrases** ...
8,jd_03_crm_operations_associate.txt,FanDuel,CRM Operations Associate,Fit Summary,2208,2161,922,The candidate's experience primarily focuses o...,The candidate's experience primarily focuses o...

In [108]:
# — Print outputs one by one for manual scoring —

for i, row in analysis_outputs_df.iterrows():
    print("=" * 120)
    print(f"Output #{i + 1}")
    print("JD Filename:", row["jd_filename"])
    print("Company:", row["company"])
    print("Title:", row["title"])
    print("Analysis Type:", row["analysis_type"])
    print("JD Context Length:", row["jd_context_length"])
    print("Resume Context Length:", row["resume_context_length"])
    print("-" * 120)
    print(row["output"])
    print("\n")

========================================================================================================================
Output #1
JD Filename: jd_01_sales_operations_analyst.txt
Company: JM Eagle
Title: Sales Operations Analyst
Analysis Type: Skill Gap Report
JD Context Length: 2381
Resume Context Length: 2418
------------------------------------------------------------------------------------------------------------------------
### Matching Skills
1. **Order & Inventory Management**: The resume mentions "Order Processing" and "Inventory Control," which aligns with the job description's emphasis on "Purchase Order Management" and "Inventory Management."
2. **E-Commerce & CRM**: The resume lists experience with various CRM systems (e.g., Monday CRM, HubSpot, PipeDrive), which matches the job description's requirement for proficiency in CRM systems.
3. **Analytics**: The resume includes proficiency in Excel, which is required in the job description.
4. **Customer Service**: The resume indicates experience in "Customer Success," which aligns with the job description's focus on providing excellent customer service.
5. **Process Improvement**: The resume mentions "Process Improvement," which corresponds to the job description's emphasis on "Process Optimization."

### Missing Skills
1. **Proficiency in AS 400**: The resume does not mention experience with AS 400, which is specified in the job description.
2. **Strong Attention to Detail**: While the resume demonstrates relevant experience, it does not explicitly mention attention to detail as a skill.
3. **Excellent Organizational Skills**: The resume does not explicitly state organizational skills, which are highlighted in the job description.
4. **Effective Communication and Interpersonal Skills**: The resume does not specifically mention these skills, although they may be implied through customer service experience.
5. **Problem-Solving Skills**: The resume does not explicitly mention problem-solving skills, which are required in the job description.

### Recommended Actions to Close the Skill Gap
1. **Gain Experience with AS 400**: Consider taking a course or seeking opportunities to work with AS 400 systems to gain familiarity and proficiency.
2. **Highlight Attention to Detail**: Update the resume to explicitly mention attention to detail, perhaps by providing examples of how this skill was applied in previous roles.
3. **Demonstrate Organizational Skills**: Include specific examples or achievements that showcase organizational skills, such as managing multiple projects or tasks simultaneously.
4. **Emphasize Communication Skills**: Add a section or bullet points that highlight effective communication and interpersonal skills, possibly through examples of collaboration with team members or stakeholders.
5. **Develop Problem-Solving Skills**: Engage in training or workshops focused on problem-solving techniques, and consider adding relevant experiences to the resume that demonstrate these skills in action.


========================================================================================================================
Output #2
JD Filename: jd_01_sales_operations_analyst.txt
Company: JM Eagle
Title: Sales Operations Analyst
Analysis Type: Keyword Alignment
JD Context Length: 2217
Resume Context Length: 2161
------------------------------------------------------------------------------------------------------------------------
| **Keywords/Phrases**                          | **Match/No Match** | **Justification**                                                                                     |
|-----------------------------------------------|---------------------|-------------------------------------------------------------------------------------------------------|
| Customer Service in manufacturing environment  | Match               | Experience in sales operations and customer support in a medical device manufacturing context.        |
| Recent college graduates or early-career professionals | No Match           | No indication of being a recent graduate or early-career professional in the resume.                  |
| Proficiency in Microsoft Excel, Word, AS 400, and/or CRM systems | Match               | Proficient in Excel and various CRM systems (Monday CRM, HubSpot, PipeDrive).                        |
| Strong attention to detail                     | Match               | Managed order processing and inventory control, ensuring compliance with quality assurance standards.  |
| Excellent organizational skills                | Match               | Oversaw order processing and managed warehouse inventory, demonstrating strong organizational skills.  |
| Effective communication and interpersonal skills | Match               | Developed process documents and templates for customer experiences, indicating strong communication skills. |
| Problem-solving skills                         | Match               | Led projects to reduce inventory holding costs and automated order processing, showcasing problem-solving abilities. |
| Prior experience in purchase order processing  | Match               | Experience in overseeing order processing through Priority ERP, which includes purchase order management. |
| Bachelor’s Degree in Business or related field | No Match           | No mention of a degree in Business or related field in the resume.                                   |
| System Proficiency                             | Match               | Utilized various systems including Priority ERP, Excel, and multiple CRM platforms.                   |
| Process Optimization                           | Match               | Implemented improved tracking notifications and automated systems to streamline workflows.             |
| Customer Service                              | Match               | Provided consistent customer experiences and support in sales operations.                             |
| Inventory Management                           | Match               | Managed warehouse inventory and performed quarterly reviews, indicating experience in inventory management. |
| Communication with customers and sales personnel | Match               | Communicated with sales teams and developed templates for customer interactions.                      |
| Product Knowledge                              | No Match           | No specific mention of obtaining product knowledge through training or self-study in the resume.     |

**Final Match Rate:** 11 Matches / 15 Keywords = 73.33% Match Rate


========================================================================================================================
Output #3
JD Filename: jd_01_sales_operations_analyst.txt
Company: JM Eagle
Title: Sales Operations Analyst
Analysis Type: Fit Summary
JD Context Length: 1920
Resume Context Length: 2161
------------------------------------------------------------------------------------------------------------------------
The candidate's experience as a Sales Operations Manager at EndyMed Medical, Inc. aligns well with the job description's emphasis on order processing and inventory management, as they oversee order processing through Priority ERP and manage warehouse inventory. Their proficiency in Microsoft Excel, as evidenced by their use of Power Query and PivotTables, meets the requirement for strong Excel skills. Additionally, their role in automating processes and improving operational efficiency demonstrates the problem-solving skills sought in the job description. However, while the candidate has relevant experience in a manufacturing environment, it is not specifically in a customer service capacity, which is preferred for this role.


========================================================================================================================
Output #4
JD Filename: jd_02_revenue_operations_associate.txt
Company: Sunbit
Title: Revenue Operations Associate
Analysis Type: Skill Gap Report
JD Context Length: 2340
Resume Context Length: 2418
------------------------------------------------------------------------------------------------------------------------
### Matching Skills
1. **Process Improvement** - The resume mentions "Process Improvement" under the Operations section, which aligns with the job description's requirement to look for ways to make processes tighter, faster, and less painful for sales.
2. **Detail-oriented** - The resume demonstrates attention to detail through various roles, particularly in managing inventory and ensuring compliance with medical device standards.
3. **Self-starter mentality** - The experience described in the resume shows initiative in automating processes and improving workflows, indicating a self-starter mentality.
4. **Experience in Sales Ops** - The candidate has experience as a Sales Operations Manager, which is relevant to the job description's requirement for experience in Sales Ops or similar roles.

### Missing Skills
1. **Experience with AI tools** - The job description specifies a requirement for comfort using AI tools, which is not mentioned in the resume.
2. **Specific tools mentioned** - The job description lists Salesforce, Outreach.io, Clay, or Nooks as nice-to-haves, none of which are present in the resume.
3. **Bachelor’s degree** - The job description requires a Bachelor’s degree, which is not mentioned in the resume.
4. **Service-oriented mindset** - While the resume demonstrates operational skills, it does not explicitly convey a service-oriented mindset or commitment to serving others before self.

### Recommended Actions to Close the Skill Gap
1. **Gain Experience with AI Tools**: The candidate should seek training or hands-on experience with AI tools relevant to sales operations, such as AI-driven CRM systems or analytics tools that incorporate AI functionalities.
2. **Familiarize with Specific Tools**: The candidate should consider gaining experience with Salesforce, Outreach.io, Clay, or Nooks through online courses, certifications, or by seeking roles that provide exposure to these platforms.
3. **Highlight Educational Background**: If the candidate has a Bachelor’s degree, they should ensure it is clearly stated on the resume. If not, they may consider pursuing a degree or relevant certifications to meet this requirement.
4. **Develop a Service-oriented Mindset**: The candidate could engage in volunteer work or customer service roles that emphasize serving others, which can help demonstrate a commitment to a service-oriented mindset in future applications. Additionally, they could include examples in their resume or cover letter that reflect empathy and commitment to team members and clients.


========================================================================================================================
Output #5
JD Filename: jd_02_revenue_operations_associate.txt
Company: Sunbit
Title: Revenue Operations Associate
Analysis Type: Keyword Alignment
JD Context Length: 2340
Resume Context Length: 2161
------------------------------------------------------------------------------------------------------------------------
| **Keywords/Phrases**                          | **Match**   | **Justification**                                                                                     |
|-----------------------------------------------|-------------|-------------------------------------------------------------------------------------------------------|
| Service-oriented mindset                      | No Match    | The resume does not explicitly mention a service-oriented mindset or prioritizing others' needs.      |
| Empathy and commitment                        | No Match    | There is no specific mention of empathy or commitment to candidates or team members in the resume.    |
| Recruitment lifecycle                         | No Match    | The resume focuses on sales operations and does not mention recruitment or the recruitment lifecycle.  |
| Ownership of processes                        | Match       | The candidate has experience in overseeing order processing and managing inventory, indicating ownership. |
| Collaboration across departments              | No Match    | The resume does not provide evidence of collaboration with internal stakeholders or departments.       |
| Inclusive hiring process                      | No Match    | There is no mention of involvement in an inclusive hiring process in the resume.                      |
| Streamline recruitment process                 | No Match    | The resume discusses process improvement but does not specifically mention recruitment processes.      |
| Enhance candidate experiences                  | No Match    | The resume does not address candidate experiences or enhancements related to recruitment.               |
| Data-driven hiring decisions                  | No Match    | The resume mentions analytics but does not connect it to hiring decisions.                            |
| Handle ad-hoc requests                        | No Match    | There is no mention of handling ad-hoc requests in the resume.                                       |
| Make processes tighter, faster, less painful  | Match       | The candidate has implemented automation and improved processes, indicating a focus on efficiency.    |
| 2–4 years of experience                       | Match       | The candidate has relevant experience in sales operations and operations coordination.                |
| Self-starter mentality                        | No Match    | The resume does not explicitly state a self-starter mentality or initiative.                          |
| Detail-oriented                               | Match       | The candidate demonstrates detail-oriented skills through inventory management and process documentation. |
| Bachelor’s degree required                    | No Match    | The resume does not mention the candidate's educational background.                                   |
| Serve others before self                      | No Match    | There is no explicit mention of serving others before self in the resume.                             |
| Comfortable using AI tools                    | No Match    | The resume does not mention experience with AI tools.                                                |
| Experience with Salesforce                    | No Match    | The resume does not mention Salesforce or related tools.                                             |
| Experience with Outreach.io                   | No Match    | The resume does not mention Outreach.io or related tools.                                            |
| Experience with Clay                          | No Match    | The resume does not mention Clay or related tools.                                                  |
| Experience with Nooks                         | No Match    | The resume does not mention Nooks or related tools.                                                 |
| Build authentic relationships                 | No Match    | The resume does not provide evidence of building relationships with candidates or hiring managers.    |
| Respond to candidates in a timely manner      | No Match    | There is no mention of responding to candidates or internal team members in a timely manner.          |
| Maintain agility                              | No Match    | The resume does not mention maintaining agility in processes or responses.                            |

**Final Match Rate:** 6/30 (20%)


========================================================================================================================
Output #6
JD Filename: jd_02_revenue_operations_associate.txt
Company: Sunbit
Title: Revenue Operations Associate
Analysis Type: Fit Summary
JD Context Length: 2387
Resume Context Length: 2161
------------------------------------------------------------------------------------------------------------------------
The candidate has relevant experience as a Sales Operations Manager, overseeing order processing and managing inventory, which aligns with the job's requirement for 2–4 years in Sales Ops or similar roles. Their experience in automating processes and improving workflows, such as reducing order processing time by 50% and developing process documents, demonstrates a self-starter mentality and a focus on making processes tighter and faster, as emphasized in the job description. Additionally, their familiarity with CRM tools and automation platforms like Zapier aligns with the need for comfort using AI tools. However, the resume does not mention specific experience with Salesforce, Outreach.io, Clay, or Nooks, which are preferred qualifications for the role.


========================================================================================================================
Output #7
JD Filename: jd_03_crm_operations_associate.txt
Company: FanDuel
Title: CRM Operations Associate
Analysis Type: Skill Gap Report
JD Context Length: 2661
Resume Context Length: 2418
------------------------------------------------------------------------------------------------------------------------
### Matching Skills
1. **SQL** - The resume lists SQL under the Analytics section, which matches the job description's requirement for comfortable querying and logic (SQL knowledge a plus).
2. **Analytics** - The resume includes various analytics tools and skills (Excel, Tableau, Google Analytics) that align with the job's emphasis on strong analytical skills.
3. **E-Commerce & CRM** - The resume mentions experience with CRM tools (HubSpot, MailChimp) which is relevant to the CRM Operations Associate role.
4. **Attention to Detail** - The resume demonstrates meticulous attention to detail through various roles, particularly in managing inventory and order processing.

### Missing Skills
1. **Email Service Provider Experience** - The job description specifies knowledge and experience with at least one email service provider (Braze, Xtremepush, Movable Ink), which is not mentioned in the resume.
2. **HTML and CSS** - The job requires a strong understanding of HTML and CSS with advanced technical capabilities, which is not present in the resume.
3. **Marketing Communications Metrics** - The job description mentions an advanced understanding of marketing communications metrics and player engagement patterns, which is not explicitly covered in the resume.
4. **Quality Assurance & Testing** - The job requires contributions to QA efforts and A/B testing, which are not mentioned in the resume.
5. **Gaming or Casino Campaign Experience** - The job requires 1-3 years of experience in email and/or mobile marketing specifically within the gaming or casino industry, which is not reflected in the resume.

### Recommended Actions to Close the Skill Gap
1. **Gain Experience with Email Service Providers**: Consider taking online courses or certifications that focus on email marketing platforms like Braze, Xtremepush, or Movable Ink. Additionally, seek opportunities to work on projects that involve these tools.

2. **Learn HTML and CSS**: Enroll in online courses or tutorials that teach HTML and CSS. Practical application through personal projects or freelance work can also help build this skill.

3. **Understand Marketing Communications Metrics**: Study marketing communications metrics through online courses or resources. Familiarize yourself with key performance indicators (KPIs) relevant to email and mobile marketing.

4. **Participate in QA and A/B Testing**: Look for opportunities to engage in quality assurance processes and A/B testing in your current role or through volunteer projects. This could involve collaborating with marketing teams to understand their testing methodologies.


# Evaluation available in separate PDF file as a table.

### Evaluation Analysis

**Which analysis type worked best?** 
The Fit Summary worked the best. Across all 3 job descriptions, the job fit summary was the only one that organized actionable insights by soft skills, technical skills, and industry experience. The fit summary had high accountability, was faithful throughout, and its list of skills was always correct, with no exaggerations or hallucinations. 

**Which JDs produced the best/worst results? Why?**
The third job description for the CRM Ops Associate yielded the best results across the 3 models. It was able to ignore the company description, job benefits, and recruitment timeline aspects of the job description, allowing for the list of skills and keyword to be most accurate. It also did an excellent job of segmenting education requirements, hard skills, and technical requirements, and the industry context and preferred professional experience in the JD. 

Contrastingly, the second job had the worst results for the opposite reasons. In the Keyword Alignment model, many of the skills were pulled from irrelevant sections of the job description. For instance, there was a retrieval of the recruitment notice section of the job description, legal notices, and very general soft skills like team player, hard-working mentality, etc. 

**Where did the system hallucinate or produce inaccurate results?**
Thankfully, the model did not provide any hallucinations thanks to the restrictions in the prompt engineering. That said, this served as a double edged sword, because a lot of the inaccurate results stemmed from the models inability to make logical reasonings from the resume to match the soft skills section of job descriptions. Nearly of the inaccurate results stemmed from very specific soft-skill listings like comments on employee "mindset", employee's "willingness to work long hours", or "maintain agility". Each job descriptions adjectives chosen for soft skills will vary significantly, thus, this caused the disconnect with the resume. Because these specific keywords were not in the resume, especially because thinks like problem-solving, collaboration, and work ethic can be inferred through professional experience, led to several no matches throughout the keyword alignment modeling. 

Furthermore, the innacurate results also seemed to stem from the education section. It seems that the resume only pulled from the professionla experience and skills section of the resume, not taking into account education. This led to a nearly every job description having the recommendation of getting a Bachelor's degree. Alternatively, the model may also lack the necessary udnerstanding of the B.A. abbreviation. 

**What would you improve?**
The first thing I would improve is a standardization of the job description input. This would require manual work, with the entry of the job description specifically removing legal hiring notices, mentions of job benefits or recruiting timeliens. Furthermore, I would engineer the prompt better so that the model has the ability to make logical conclusions with regards to soft skills. For instance, because the LLM is acting as a recruiter, it can make inferences about an applicants work ethic, leadership, or collaboration skills based on a strong professional job history. Alternatively, the model can ignore soft skills as a list of keywords entirely, making the application of the job fit solely technical, or hard skill focused.

---

## Next Steps

1. Build your Streamlit app (`streamlit_app.py`) using the pipeline from this notebook
2. Write your Technical Manager Memo (`memo.md`)
3. Complete your AI Usage Log (`ai_log.md`)
4. Verify GitHub repository structure and commit count

---
*BSAN 6200 | Spring 2026 | Assignment 5 — Option B*